"""Public package exports for the canonical 4.0.0 Decision Moment V1 release.

This release publishes the fail-closed cutover surface for:

- canonical mission taxonomy: ``mission_slug``, ``mission_number``, ``mission_type``
- canonical catalog events: ``MissionCreated`` and ``MissionClosed``
- explicit envelope identity split: ``build_id`` versus ``node_id``
- authoritative artifact-driven compatibility gating via ``spec_kitty_events.cutover``
- Decision Moment V1: discriminated-union DecisionPoint payloads, Widened event,
  interview-origin fields, terminal outcome rules, and shared V1 models
"""

__version__ = "4.0.0"

from spec_kitty_events.cutover import (
    CUTOVER_ARTIFACT,
    CutoverArtifact,
    accepted_major_matches,
    assert_canonical_cutover_signal,
    canonical_signal_field_name,
    canonical_signal_location,
    forbidden_legacy_aggregate_names,
    forbidden_legacy_event_names,
    forbidden_legacy_keys,
    is_pre_cutover_payload,
    load_cutover_artifact,
    read_cutover_signal,
    required_cutover_value_matches,
)

# Core data models
from spec_kitty_events.models import (
    Event,
    ErrorEntry,
    ConflictResolution,
    SpecKittyEventsError,
    StorageError,
    ValidationError,
    CyclicDependencyError,
    normalize_event_id,
)

# Storage abstractions
from spec_kitty_events.storage import (
    EventStore,
    ClockStorage,
    ErrorStorage,
    InMemoryEventStore,
    InMemoryClockStorage,
    InMemoryErrorStorage,
)

# Lamport clock
from spec_kitty_events.clock import LamportClock

# Conflict detection
from spec_kitty_events.conflict import (
    is_concurrent,
    total_order_key,
)

# Topological sorting
from spec_kitty_events.topology import topological_sort

# CRDT merge functions
from spec_kitty_events.crdt import (
    merge_gset,
    merge_counter,
)

# State-machine merge
from spec_kitty_events.merge import state_machine_merge

# Error logging
from spec_kitty_events.error_log import ErrorLog

# Gate observability contracts
from spec_kitty_events.gates import (
    GatePayloadBase,
    GatePassedPayload,
    GateFailedPayload,
    UnknownConclusionError,
    map_check_run_conclusion,
)

# Lifecycle event contracts
from spec_kitty_events.lifecycle import (
    SCHEMA_VERSION,
    MISSION_CREATED,
    MISSION_CLOSED,
    MISSION_STARTED,
    MISSION_COMPLETED,
    MISSION_CANCELLED,
    PHASE_ENTERED,
    REVIEW_ROLLBACK,
    MISSION_EVENT_TYPES,
    TERMINAL_MISSION_STATUSES,
    MissionStatus,
    MissionCreatedPayload,
    MissionClosedPayload,
    MissionStartedPayload,
    MissionCompletedPayload,
    MissionCancelledPayload,
    PhaseEnteredPayload,
    ReviewRollbackPayload,
    LifecycleAnomaly,
    ReducedMissionState,
    reduce_lifecycle_events,
)

# Status state model contracts
from spec_kitty_events.status import (
    Lane,
    SyncLaneV1,
    SyncLaneV2,
    CANONICAL_TO_SYNC_V1,
    CANONICAL_TO_SYNC_V2,
    canonical_to_sync_v1,
    canonical_to_sync_v2,
    ExecutionMode,
    RepoEvidence,
    VerificationEntry,
    ReviewVerdict,
    DoneEvidence,
    ForceMetadata,
    StatusTransitionPayload,
    TransitionError,
    TransitionValidationResult,
    normalize_lane,
    validate_transition,
    TERMINAL_LANES,
    LANE_ALIASES,
    WP_STATUS_CHANGED,
    status_event_sort_key,
    dedup_events,
    reduce_status_events,
    WPState,
    TransitionAnomaly,
    ReducedStatus,
)

# Collaboration event contracts
from spec_kitty_events.collaboration import (
    PARTICIPANT_INVITED,
    PARTICIPANT_JOINED,
    PARTICIPANT_LEFT,
    PRESENCE_HEARTBEAT,
    DRIVE_INTENT_SET,
    FOCUS_CHANGED,
    PROMPT_STEP_EXECUTION_STARTED,
    PROMPT_STEP_EXECUTION_COMPLETED,
    CONCURRENT_DRIVER_WARNING,
    POTENTIAL_STEP_COLLISION_DETECTED,
    WARNING_ACKNOWLEDGED,
    COMMENT_POSTED,
    DECISION_CAPTURED,
    SESSION_LINKED,
    COLLABORATION_EVENT_TYPES,
    ParticipantIdentity,
    AuthPrincipalBinding,
    FocusTarget,
    ParticipantInvitedPayload,
    ParticipantJoinedPayload,
    ParticipantLeftPayload,
    ParticipantExternalRefs,
    PresenceHeartbeatPayload,
    DriveIntentSetPayload,
    FocusChangedPayload,
    PromptStepExecutionStartedPayload,
    PromptStepExecutionCompletedPayload,
    ConcurrentDriverWarningPayload,
    PotentialStepCollisionDetectedPayload,
    WarningAcknowledgedPayload,
    CommentPostedPayload,
    DecisionCapturedPayload,
    SessionLinkedPayload,
    ReducedCollaborationState,
    CollaborationAnomaly,
    UnknownParticipantError,
    reduce_collaboration_events,
)

# Glossary semantic integrity contracts
from spec_kitty_events.glossary import (
    GLOSSARY_SCOPE_ACTIVATED,
    TERM_CANDIDATE_OBSERVED,
    SEMANTIC_CHECK_EVALUATED,
    GLOSSARY_CLARIFICATION_REQUESTED,
    GLOSSARY_CLARIFICATION_RESOLVED,
    GLOSSARY_SENSE_UPDATED,
    GENERATION_BLOCKED_BY_SEMANTIC_CONFLICT,
    GLOSSARY_STRICTNESS_SET,
    GLOSSARY_EVENT_TYPES,
    SemanticConflictEntry,
    GlossaryScopeActivatedPayload,
    TermCandidateObservedPayload,
    SemanticCheckEvaluatedPayload,
    GlossaryClarificationRequestedPayload,
    GlossaryClarificationResolvedPayload,
    GlossarySenseUpdatedPayload,
    GenerationBlockedBySemanticConflictPayload,
    GlossaryStrictnessSetPayload,
    GlossaryAnomaly,
    ClarificationRecord,
    ReducedGlossaryState,
    reduce_glossary_events,
)

# Mission-next runtime contracts
from spec_kitty_events.mission_next import (
    MISSION_RUN_STARTED,
    NEXT_STEP_PLANNED,
    NEXT_STEP_ISSUED,
    NEXT_STEP_AUTO_COMPLETED,
    DECISION_INPUT_REQUESTED,
    DECISION_INPUT_ANSWERED,
    MISSION_RUN_COMPLETED,
    MISSION_NEXT_EVENT_TYPES,
    MissionRunStatus,
    TERMINAL_RUN_STATUSES,
    RuntimeActorIdentity,
    MissionRunStartedPayload,
    NextStepIssuedPayload,
    NextStepAutoCompletedPayload,
    DecisionInputRequestedPayload,
    DecisionInputAnsweredPayload,
    MissionRunCompletedPayload,
    MissionNextAnomaly,
    ReducedMissionRunState,
    reduce_mission_next_events,
)

# Analytics event contracts
from spec_kitty_events.analytics import (
    TOKEN_USAGE_RECORDED,
    DIFF_SUMMARY_RECORDED,
    ANALYTICS_EVENT_TYPES,
    TokenUsageRecordedPayload,
    DiffSummaryRecordedPayload,
)

# Dossier event contracts (v2.4.0)
from spec_kitty_events.dossier import (
    MISSION_DOSSIER_ARTIFACT_INDEXED,
    MISSION_DOSSIER_ARTIFACT_MISSING,
    MISSION_DOSSIER_SNAPSHOT_COMPUTED,
    MISSION_DOSSIER_PARITY_DRIFT_DETECTED,
    DOSSIER_EVENT_TYPES,
    NamespaceMixedStreamError,
    LocalNamespaceTuple,
    ArtifactIdentity,
    ContentHashRef,
    ProvenanceRef,
    MissionDossierArtifactIndexedPayload,
    MissionDossierArtifactMissingPayload,
    MissionDossierSnapshotComputedPayload,
    MissionDossierParityDriftDetectedPayload,
    ArtifactEntry,
    AnomalyEntry,
    SnapshotSummary,
    DriftRecord,
    MissionDossierState,
    reduce_mission_dossier,
)

# Mission Audit Lifecycle Contracts (2.5.0)
from spec_kitty_events.mission_audit import (
    AUDIT_SCHEMA_VERSION as AUDIT_SCHEMA_VERSION,
    MISSION_AUDIT_REQUESTED as MISSION_AUDIT_REQUESTED,
    MISSION_AUDIT_STARTED as MISSION_AUDIT_STARTED,
    MISSION_AUDIT_DECISION_REQUESTED as MISSION_AUDIT_DECISION_REQUESTED,
    MISSION_AUDIT_COMPLETED as MISSION_AUDIT_COMPLETED,
    MISSION_AUDIT_FAILED as MISSION_AUDIT_FAILED,
    MISSION_AUDIT_EVENT_TYPES as MISSION_AUDIT_EVENT_TYPES,
    TERMINAL_AUDIT_STATUSES as TERMINAL_AUDIT_STATUSES,
    AuditVerdict as AuditVerdict,
    AuditSeverity as AuditSeverity,
    AuditStatus as AuditStatus,
    AuditArtifactRef as AuditArtifactRef,
    PendingDecision as PendingDecision,
    MissionAuditAnomaly as MissionAuditAnomaly,
    MissionAuditRequestedPayload as MissionAuditRequestedPayload,
    MissionAuditStartedPayload as MissionAuditStartedPayload,
    MissionAuditDecisionRequestedPayload as MissionAuditDecisionRequestedPayload,
    MissionAuditCompletedPayload as MissionAuditCompletedPayload,
    MissionAuditFailedPayload as MissionAuditFailedPayload,
    ReducedMissionAuditState as ReducedMissionAuditState,
    reduce_mission_audit_events as reduce_mission_audit_events,
)

# DecisionPoint Lifecycle Contracts (4.0.0 / V1)
from spec_kitty_events.decisionpoint import (
    DECISIONPOINT_SCHEMA_VERSION as DECISIONPOINT_SCHEMA_VERSION,
    DECISION_POINT_OPENED as DECISION_POINT_OPENED,
    DECISION_POINT_DISCUSSING as DECISION_POINT_DISCUSSING,
    DECISION_POINT_RESOLVED as DECISION_POINT_RESOLVED,
    DECISION_POINT_OVERRIDDEN as DECISION_POINT_OVERRIDDEN,
    DECISION_POINT_WIDENED as DECISION_POINT_WIDENED,
    DECISION_POINT_EVENT_TYPES as DECISION_POINT_EVENT_TYPES,
    DecisionPointState as DecisionPointState,
    DecisionAuthorityRole as DecisionAuthorityRole,
    DecisionPointAnomaly as DecisionPointAnomaly,
    DecisionPointOpenedPayload as DecisionPointOpenedPayload,
    DecisionPointOpenedAdrPayload as DecisionPointOpenedAdrPayload,
    DecisionPointOpenedInterviewPayload as DecisionPointOpenedInterviewPayload,
    DecisionPointDiscussingPayload as DecisionPointDiscussingPayload,
    DecisionPointDiscussingAdrPayload as DecisionPointDiscussingAdrPayload,
    DecisionPointDiscussingInterviewPayload as DecisionPointDiscussingInterviewPayload,
    DecisionPointResolvedPayload as DecisionPointResolvedPayload,
    DecisionPointResolvedAdrPayload as DecisionPointResolvedAdrPayload,
    DecisionPointResolvedInterviewPayload as DecisionPointResolvedInterviewPayload,
    DecisionPointOverriddenPayload as DecisionPointOverriddenPayload,
    DecisionPointWidenedPayload as DecisionPointWidenedPayload,
    ReducedDecisionPointState as ReducedDecisionPointState,
    reduce_decision_point_events as reduce_decision_point_events,
)

# Decision Moment V1 shared models (4.0.0)
from spec_kitty_events.decision_moment import (
    ClosureMessageRef,
    DefaultChannelRef,
    DiscussingSnapshotKind,
    OriginFlow,
    OriginSurface,
    SummaryBlock,
    SummarySource,
    TeamspaceRef,
    TerminalOutcome,
    ThreadRef,
    WideningChannel,
    WideningProjection,
)

# Connector Lifecycle Contracts (2.7.0) — extended in 2.8.0
from spec_kitty_events.connector import (
    CONNECTOR_SCHEMA_VERSION as CONNECTOR_SCHEMA_VERSION,
    CONNECTOR_PROVISIONED as CONNECTOR_PROVISIONED,
    CONNECTOR_HEALTH_CHECKED as CONNECTOR_HEALTH_CHECKED,
    CONNECTOR_DEGRADED as CONNECTOR_DEGRADED,
    CONNECTOR_REVOKED as CONNECTOR_REVOKED,
    CONNECTOR_RECONNECTED as CONNECTOR_RECONNECTED,
    CONNECTOR_EVENT_TYPES as CONNECTOR_EVENT_TYPES,
    ConnectorState as ConnectorState,
    HealthStatus as HealthStatus,
    ReconnectStrategy as ReconnectStrategy,
    ConnectorAnomaly as ConnectorAnomaly,
    ConnectorProvisionedPayload as ConnectorProvisionedPayload,
    ConnectorHealthCheckedPayload as ConnectorHealthCheckedPayload,
    ConnectorDegradedPayload as ConnectorDegradedPayload,
    ConnectorRevokedPayload as ConnectorRevokedPayload,
    ConnectorReconnectedPayload as ConnectorReconnectedPayload,
    USER_CONNECTED as USER_CONNECTED,
    USER_DISCONNECTED as USER_DISCONNECTED,
    UserConnectedPayload as UserConnectedPayload,
    UserDisconnectedPayload as UserDisconnectedPayload,
    UserConnectionStatus as UserConnectionStatus,
    ReducedConnectorState as ReducedConnectorState,
    reduce_connector_events as reduce_connector_events,
)

# Sync Lifecycle Contracts (2.7.0)
from spec_kitty_events.sync import (
    SYNC_SCHEMA_VERSION as SYNC_SCHEMA_VERSION,
    SYNC_INGEST_ACCEPTED as SYNC_INGEST_ACCEPTED,
    SYNC_INGEST_REJECTED as SYNC_INGEST_REJECTED,
    SYNC_RETRY_SCHEDULED as SYNC_RETRY_SCHEDULED,
    SYNC_DEAD_LETTERED as SYNC_DEAD_LETTERED,
    SYNC_REPLAY_COMPLETED as SYNC_REPLAY_COMPLETED,
    SYNC_EVENT_TYPES as SYNC_EVENT_TYPES,
    EXTERNAL_REFERENCE_LINKED as EXTERNAL_REFERENCE_LINKED,
    SyncOutcome as SyncOutcome,
    SyncAnomaly as SyncAnomaly,
    SyncIngestAcceptedPayload as SyncIngestAcceptedPayload,
    SyncIngestRejectedPayload as SyncIngestRejectedPayload,
    SyncRetryScheduledPayload as SyncRetryScheduledPayload,
    SyncDeadLetteredPayload as SyncDeadLetteredPayload,
    SyncReplayCompletedPayload as SyncReplayCompletedPayload,
    ExternalReferenceLinkedPayload as ExternalReferenceLinkedPayload,
    ReducedSyncState as ReducedSyncState,
    reduce_sync_events as reduce_sync_events,
)

# Profile invocation contracts (3.1.0)
from spec_kitty_events.profile_invocation import (
    PROFILE_INVOCATION_SCHEMA_VERSION as PROFILE_INVOCATION_SCHEMA_VERSION,
    PROFILE_INVOCATION_STARTED as PROFILE_INVOCATION_STARTED,
    PROFILE_INVOCATION_COMPLETED as PROFILE_INVOCATION_COMPLETED,
    PROFILE_INVOCATION_FAILED as PROFILE_INVOCATION_FAILED,
    PROFILE_INVOCATION_EVENT_TYPES as PROFILE_INVOCATION_EVENT_TYPES,
    PROFILE_INVOCATION_RESERVED_TYPES as PROFILE_INVOCATION_RESERVED_TYPES,
    ProfileInvocationStartedPayload as ProfileInvocationStartedPayload,
)

# Retrospective contracts (3.1.0)
from spec_kitty_events.retrospective import (
    RETROSPECTIVE_SCHEMA_VERSION as RETROSPECTIVE_SCHEMA_VERSION,
    RETROSPECTIVE_COMPLETED as RETROSPECTIVE_COMPLETED,
    RETROSPECTIVE_SKIPPED as RETROSPECTIVE_SKIPPED,
    RETROSPECTIVE_EVENT_TYPES as RETROSPECTIVE_EVENT_TYPES,
    RetrospectiveCompletedPayload as RetrospectiveCompletedPayload,
    RetrospectiveSkippedPayload as RetrospectiveSkippedPayload,
    TriggerSourceT as TriggerSourceT,
)

# Backward-compatible dossier aliases without the Payload suffix.
# Older consumers import these names directly.
MissionDossierArtifactIndexed = MissionDossierArtifactIndexedPayload
MissionDossierArtifactMissing = MissionDossierArtifactMissingPayload
MissionDossierSnapshotComputed = MissionDossierSnapshotComputedPayload
MissionDossierParityDriftDetected = MissionDossierParityDriftDetectedPayload

# Public API (controls what's exported with "from spec_kitty_events import *")
__all__ = [
    # Version
    "__version__",
    # Cutover artifact
    "CUTOVER_ARTIFACT",
    "CutoverArtifact",
    "load_cutover_artifact",
    "canonical_signal_field_name",
    "canonical_signal_location",
    "read_cutover_signal",
    "accepted_major_matches",
    "required_cutover_value_matches",
    "forbidden_legacy_keys",
    "forbidden_legacy_event_names",
    "forbidden_legacy_aggregate_names",
    "is_pre_cutover_payload",
    "assert_canonical_cutover_signal",
    # Models
    "Event",
    "ErrorEntry",
    "ConflictResolution",
    "normalize_event_id",
    # Exceptions
    "SpecKittyEventsError",
    "StorageError",
    "ValidationError",
    "CyclicDependencyError",
    # Storage
    "EventStore",
    "ClockStorage",
    "ErrorStorage",
    "InMemoryEventStore",
    "InMemoryClockStorage",
    "InMemoryErrorStorage",
    # Clock
    "LamportClock",
    # Conflict detection
    "is_concurrent",
    "total_order_key",
    "topological_sort",
    # Merge functions
    "merge_gset",
    "merge_counter",
    "state_machine_merge",
    # Error logging
    "ErrorLog",
    # Gate observability
    "GatePayloadBase",
    "GatePassedPayload",
    "GateFailedPayload",
    "UnknownConclusionError",
    "map_check_run_conclusion",
    # Lifecycle event contracts
    "SCHEMA_VERSION",
    "MISSION_CREATED",
    "MISSION_CLOSED",
    "MISSION_STARTED",
    "MISSION_COMPLETED",
    "MISSION_CANCELLED",
    "PHASE_ENTERED",
    "REVIEW_ROLLBACK",
    "MISSION_EVENT_TYPES",
    "TERMINAL_MISSION_STATUSES",
    "MissionStatus",
    "MissionCreatedPayload",
    "MissionClosedPayload",
    "MissionStartedPayload",
    "MissionCompletedPayload",
    "MissionCancelledPayload",
    "PhaseEnteredPayload",
    "ReviewRollbackPayload",
    "LifecycleAnomaly",
    "ReducedMissionState",
    "reduce_lifecycle_events",
    # Status state model
    "Lane",
    "SyncLaneV1",
    "SyncLaneV2",
    "CANONICAL_TO_SYNC_V1",
    "CANONICAL_TO_SYNC_V2",
    "canonical_to_sync_v1",
    "canonical_to_sync_v2",
    "ExecutionMode",
    "RepoEvidence",
    "VerificationEntry",
    "ReviewVerdict",
    "DoneEvidence",
    "ForceMetadata",
    "StatusTransitionPayload",
    "TransitionError",
    "TransitionValidationResult",
    "normalize_lane",
    "validate_transition",
    "TERMINAL_LANES",
    "LANE_ALIASES",
    "WP_STATUS_CHANGED",
    "status_event_sort_key",
    "dedup_events",
    "reduce_status_events",
    "WPState",
    "TransitionAnomaly",
    "ReducedStatus",
    # Collaboration event contracts
    "PARTICIPANT_INVITED",
    "PARTICIPANT_JOINED",
    "PARTICIPANT_LEFT",
    "PRESENCE_HEARTBEAT",
    "DRIVE_INTENT_SET",
    "FOCUS_CHANGED",
    "PROMPT_STEP_EXECUTION_STARTED",
    "PROMPT_STEP_EXECUTION_COMPLETED",
    "CONCURRENT_DRIVER_WARNING",
    "POTENTIAL_STEP_COLLISION_DETECTED",
    "WARNING_ACKNOWLEDGED",
    "COMMENT_POSTED",
    "DECISION_CAPTURED",
    "SESSION_LINKED",
    "COLLABORATION_EVENT_TYPES",
    "ParticipantIdentity",
    "AuthPrincipalBinding",
    "FocusTarget",
    "ParticipantExternalRefs",
    "ParticipantInvitedPayload",
    "ParticipantJoinedPayload",
    "ParticipantLeftPayload",
    "PresenceHeartbeatPayload",
    "DriveIntentSetPayload",
    "FocusChangedPayload",
    "PromptStepExecutionStartedPayload",
    "PromptStepExecutionCompletedPayload",
    "ConcurrentDriverWarningPayload",
    "PotentialStepCollisionDetectedPayload",
    "WarningAcknowledgedPayload",
    "CommentPostedPayload",
    "DecisionCapturedPayload",
    "SessionLinkedPayload",
    "ReducedCollaborationState",
    "CollaborationAnomaly",
    "UnknownParticipantError",
    "reduce_collaboration_events",
    # Glossary semantic integrity contracts
    "GLOSSARY_SCOPE_ACTIVATED",
    "TERM_CANDIDATE_OBSERVED",
    "SEMANTIC_CHECK_EVALUATED",
    "GLOSSARY_CLARIFICATION_REQUESTED",
    "GLOSSARY_CLARIFICATION_RESOLVED",
    "GLOSSARY_SENSE_UPDATED",
    "GENERATION_BLOCKED_BY_SEMANTIC_CONFLICT",
    "GLOSSARY_STRICTNESS_SET",
    "GLOSSARY_EVENT_TYPES",
    "SemanticConflictEntry",
    "GlossaryScopeActivatedPayload",
    "TermCandidateObservedPayload",
    "SemanticCheckEvaluatedPayload",
    "GlossaryClarificationRequestedPayload",
    "GlossaryClarificationResolvedPayload",
    "GlossarySenseUpdatedPayload",
    "GenerationBlockedBySemanticConflictPayload",
    "GlossaryStrictnessSetPayload",
    "GlossaryAnomaly",
    "ClarificationRecord",
    "ReducedGlossaryState",
    "reduce_glossary_events",
    # Mission-next runtime contracts
    "MISSION_RUN_STARTED",
    "NEXT_STEP_PLANNED",
    "NEXT_STEP_ISSUED",
    "NEXT_STEP_AUTO_COMPLETED",
    "DECISION_INPUT_REQUESTED",
    "DECISION_INPUT_ANSWERED",
    "MISSION_RUN_COMPLETED",
    "MISSION_NEXT_EVENT_TYPES",
    "MissionRunStatus",
    "TERMINAL_RUN_STATUSES",
    "RuntimeActorIdentity",
    "MissionRunStartedPayload",
    "NextStepIssuedPayload",
    "NextStepAutoCompletedPayload",
    "DecisionInputRequestedPayload",
    "DecisionInputAnsweredPayload",
    "MissionRunCompletedPayload",
    "MissionNextAnomaly",
    "ReducedMissionRunState",
    "reduce_mission_next_events",
    # Dossier event contracts
    "MISSION_DOSSIER_ARTIFACT_INDEXED",
    "MISSION_DOSSIER_ARTIFACT_MISSING",
    "MISSION_DOSSIER_SNAPSHOT_COMPUTED",
    "MISSION_DOSSIER_PARITY_DRIFT_DETECTED",
    "DOSSIER_EVENT_TYPES",
    "NamespaceMixedStreamError",
    "LocalNamespaceTuple",
    "ArtifactIdentity",
    "ContentHashRef",
    "ProvenanceRef",
    "MissionDossierArtifactIndexedPayload",
    "MissionDossierArtifactMissingPayload",
    "MissionDossierSnapshotComputedPayload",
    "MissionDossierParityDriftDetectedPayload",
    "MissionDossierArtifactIndexed",
    "MissionDossierArtifactMissing",
    "MissionDossierSnapshotComputed",
    "MissionDossierParityDriftDetected",
    "ArtifactEntry",
    "AnomalyEntry",
    "SnapshotSummary",
    "DriftRecord",
    "MissionDossierState",
    "reduce_mission_dossier",
    # Mission Audit Lifecycle Contracts (2.5.0)
    "AUDIT_SCHEMA_VERSION",
    "MISSION_AUDIT_REQUESTED",
    "MISSION_AUDIT_STARTED",
    "MISSION_AUDIT_DECISION_REQUESTED",
    "MISSION_AUDIT_COMPLETED",
    "MISSION_AUDIT_FAILED",
    "MISSION_AUDIT_EVENT_TYPES",
    "TERMINAL_AUDIT_STATUSES",
    "AuditVerdict",
    "AuditSeverity",
    "AuditStatus",
    "AuditArtifactRef",
    "PendingDecision",
    "MissionAuditAnomaly",
    "MissionAuditRequestedPayload",
    "MissionAuditStartedPayload",
    "MissionAuditDecisionRequestedPayload",
    "MissionAuditCompletedPayload",
    "MissionAuditFailedPayload",
    "ReducedMissionAuditState",
    "reduce_mission_audit_events",
    # DecisionPoint Lifecycle Contracts (4.0.0 / V1)
    "DECISIONPOINT_SCHEMA_VERSION",
    "DECISION_POINT_DISCUSSING",
    "DECISION_POINT_EVENT_TYPES",
    "DECISION_POINT_OPENED",
    "DECISION_POINT_OVERRIDDEN",
    "DECISION_POINT_RESOLVED",
    "DECISION_POINT_WIDENED",
    "DecisionAuthorityRole",
    "DecisionPointAnomaly",
    "DecisionPointDiscussingAdrPayload",
    "DecisionPointDiscussingInterviewPayload",
    "DecisionPointDiscussingPayload",
    "DecisionPointOpenedAdrPayload",
    "DecisionPointOpenedInterviewPayload",
    "DecisionPointOpenedPayload",
    "DecisionPointOverriddenPayload",
    "DecisionPointResolvedAdrPayload",
    "DecisionPointResolvedInterviewPayload",
    "DecisionPointResolvedPayload",
    "DecisionPointState",
    "DecisionPointWidenedPayload",
    "ReducedDecisionPointState",
    "reduce_decision_point_events",
    # Decision Moment V1 shared models (4.0.0)
    "ClosureMessageRef",
    "DefaultChannelRef",
    "DiscussingSnapshotKind",
    "OriginFlow",
    "OriginSurface",
    "SummaryBlock",
    "SummarySource",
    "TeamspaceRef",
    "TerminalOutcome",
    "ThreadRef",
    "WideningChannel",
    "WideningProjection",
    # Connector Lifecycle Contracts (2.7.0)
    "CONNECTOR_SCHEMA_VERSION",
    "CONNECTOR_PROVISIONED",
    "CONNECTOR_HEALTH_CHECKED",
    "CONNECTOR_DEGRADED",
    "CONNECTOR_REVOKED",
    "CONNECTOR_RECONNECTED",
    "CONNECTOR_EVENT_TYPES",
    "ConnectorState",
    "HealthStatus",
    "ReconnectStrategy",
    "ConnectorAnomaly",
    "ConnectorProvisionedPayload",
    "ConnectorHealthCheckedPayload",
    "ConnectorDegradedPayload",
    "ConnectorRevokedPayload",
    "ConnectorReconnectedPayload",
    "USER_CONNECTED",
    "USER_DISCONNECTED",
    "UserConnectedPayload",
    "UserDisconnectedPayload",
    "UserConnectionStatus",
    "ReducedConnectorState",
    "reduce_connector_events",
    # Sync Lifecycle Contracts (2.7.0)
    "SYNC_SCHEMA_VERSION",
    "SYNC_INGEST_ACCEPTED",
    "SYNC_INGEST_REJECTED",
    "SYNC_RETRY_SCHEDULED",
    "SYNC_DEAD_LETTERED",
    "SYNC_REPLAY_COMPLETED",
    "SYNC_EVENT_TYPES",
    "EXTERNAL_REFERENCE_LINKED",
    "SyncOutcome",
    "SyncAnomaly",
    "SyncIngestAcceptedPayload",
    "SyncIngestRejectedPayload",
    "SyncRetryScheduledPayload",
    "SyncDeadLetteredPayload",
    "SyncReplayCompletedPayload",
    "ExternalReferenceLinkedPayload",
    "ReducedSyncState",
    "reduce_sync_events",
    # Profile invocation contracts (3.1.0)
    "PROFILE_INVOCATION_SCHEMA_VERSION",
    "PROFILE_INVOCATION_STARTED",
    "PROFILE_INVOCATION_COMPLETED",
    "PROFILE_INVOCATION_FAILED",
    "PROFILE_INVOCATION_EVENT_TYPES",
    "PROFILE_INVOCATION_RESERVED_TYPES",
    "ProfileInvocationStartedPayload",
    # Retrospective contracts (3.1.0)
    "RETROSPECTIVE_SCHEMA_VERSION",
    "RETROSPECTIVE_COMPLETED",
    "RETROSPECTIVE_SKIPPED",
    "RETROSPECTIVE_EVENT_TYPES",
    "RetrospectiveCompletedPayload",
    "RetrospectiveSkippedPayload",
    "TriggerSourceT",
]
